d={}
name=input("Enter name1: ")
lang=input("Enter his fav lang: ")
d.update({name:lang})
name=input("Enter name2: ")
lang=input("Enter his fav lang: ")
d.update({name:lang})
name=input("Enter name3: ")
lang=input("Enter his fav lang: ")
d.update({name:lang})
name=input("Enter name4: ")
lang=input("Enter his fav lang: ")
d.update({name:lang})
print(d)